version: '3'

services:
  mysqlapp:
    image: mixaverross88/java-e-commerce-mysql:1.0
    enviroment:
      - MYSQL_ROOT_PASSWORD=kdiosk33
    ports:
      - 3306:3306
    networks:
      - isolated
  javaecommerce:
    image: mixaverross88/java-e-commerce:3.0
    ports:
      - 8080:8080
      - 9990:9990
    networks:
      - isolated

secrets:
  mysql_root_pass:
    external: true
